const types = {
  ADD_REQUEST: 'ADD_REQUEST',
  ADD_SUCCESS: 'ADD_SUCCESS',
  ADD_FAILURE: 'ADD_FAILURE',

  UPDATE_REQUEST: 'UPDATE_REQUEST',
  UPDATE_SUCCESS: 'UPDATE_SUCCESS',
  UPDATE_FAILURE: 'UPDATE_FAILURE',

  DELETE_REQUEST: 'DELETE_REQUEST',
  DELETE_SUCCESS: 'DELETE_SUCCESS',
  DELETE_FAILURE: 'DELETE_FAILURE',

  PAGINATE_REQUEST: 'PAGINATE_REQUEST',
  PAGINATE_SUCCESS: 'PAGINATE_SUCCESS',
  PAGINATE_FAILURE: 'PAGINATE_FAILURE',

  SEARCH_PAGINATE_REQUEST: 'SEARCH_PAGINATE_REQUEST',
  SEARCH_PAGINATE_SUCCESS: 'SEARCH_PAGINATE_SUCCESS',
  SEARCH_PAGINATE_FAILURE: 'SEARCH_PAGINATE_FAILURE',
};

export default types;
